CREATE TABLE IF NOT EXISTS post (
  id INT AUTO_INCREMENT NOT NULL,
  title VARCHAR(128) NOT NULL,
  url VARCHAR(128) NOT NULL,
  tag VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  PRIMARY KEY (`id`)
);
